name: ml_labs
channels:
  - pytorch
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.4.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.9
  - click=8.0.3
  - cpuonly=2.0
  - cryptography=3.4.8
  - cudatoolkit=11.0.221
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_resources=5.4.0
  - intel-openmp=2021.4.0
  - ipykernel=5.5.5
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.2.1
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.9.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.7.3
  - nltk=3.6.5
  - notebook=6.4.6
  - numexpr=2.7.3
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.4
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1
  - regex=2021.8.3
  - requests=2.26.0
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.36.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - torchaudio=0.10.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - ipywidgets==7.6.5
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyterlab-widgets==1.0.2
    - numpy==1.21.4
    - pillow==4.0.0
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - threadpoolctl==3.0.0
    - torch==1.10.1
    - torchvision==0.11.2
    - typing-extensions==4.0.1
    - widgetsnbextension==3.5.2
    - wordcloud==1.8.1
